### ISSUE TITLE
License for modestmaps

### ISSUE THREAD

**Issue by dakshshah96** [stamen/modestmaps-js#149]
Hey @tmcw,

I'd like to host your library, modestmaps on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

We need to know what license your project comes under so we can mention it appropriately.

If it's not too much to ask, can you please add the license of your project to the repository (e.g. MIT, Apache-2.0, etc.)

**Comment by almccon** [comment]
@dakshshah96 The README says that the project is BSD-licensed.

**Comment by dakshshah96** [comment]
@almccon Any idea about what specific BSD license is it? You can refer https://spdx.org/licenses/ for the list of specific licenses we need to mention along with this project.
